#! /bin/bash

. `dirname $0`/../config
. `dirname $0`/utils

IFS="
"

mkdir -p ${EXPORTS}
mkdir -p ${RECORDINGS}
mkdir -p ${PIDS}

function at_exit()
{
  pkill -P $$
  rm -f ${PIDS}/converter.pid
  rm -f ${PIDS}/converter-service.pid
}
trap at_exit EXIT
trap at_exit SIGINT SIGKILL

log "Converter service started."
echo "$$" > ${PIDS}/converter-service.pid
while true; do

  for TS in `ls -t ${EXPORTS}/*.ts 2>/dev/null`; do
    FULLNAME=`basename "${TS}" | sed -e "s/.ts$//"`
    log "Converting ${FULLNAME}.ts"

    ffmpeg -loglevel fatal -y -i "${EXPORTS}/${FULLNAME}.ts" \
           -vf yadif -movflags faststart "${EXPORTS}/${FULLNAME}.mp4"
    if [ $? -eq 0 ]; then
      log "Conversion complete."
      rm "${EXPORTS}/${FULLNAME}.ts"
      mv "${EXPORTS}/${FULLNAME}.mp4" "${RECORDINGS}/${FULLNAME}.mp4"
    else
      log "Error: Conversion failed. Saved transport stream as ${RECORDINGS}/${FULLNAME}.ts.fail."
      rm -f "${EXPORTS}/${FULLNAME}.mp4"
      mv "${EXPORTS}/${FULLNAME}.ts" "${RECORDINGS}/${FULLNAME}.ts.fail"
    fi
  done

  log "Waiting for next job."
  named_sleep converter

done
